# 220116(일)

# 오늘 공부한 것

- Deep dive 45장 프로미스

# 기억해야 할 것

### 45 프로미스

프로미스는 전통적인 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있는 장점을 가지고 있다.

### 45.1 비동기 처리를 위한 콜백 패턴의 단점

**45.1.1 콜백 헬**

```jsx
const get = (URL) => {
  const xhr = new XMLHttpRequest()
  xhr.open('GET', URL)
  xhr.send()

  xhr.onload = () => {
    if (xhr.status === 200) {
      console.log('in get function response', JSON.parse(xhr.response))
      // 데이터 잘 나옴
      return JSON.parse(xhr.response)
    }
    console.error('ERROR!')
  }
}

const response = get('https://jsonplaceholder.typicode.com/posts/1')
console.log('out response', response) // undefined
```

- 위 코드를 실행하면 출력이
  out response undfined
  in get function response {데이터}로 나온다.
- 밖에 선언된 console이 먼저 실행되고 그로 인해 값이 undefined가 나오게 되는데 그 이유는 **onload 이벤트 핸들러가 비동기**로 동작하기 때문이다.
- 즉, get함수는 onload가 실행되기 전에 get함수는 끝나며 return이 생략되어 있기 때문에 undefined를 리턴하게 된다. 그러므로 onload에서의 return은 아무런 영향을 미치지 않는다.

**상위 스코프 변수 할당**

```jsx
let todo
const get = (URL) => {
  const xhr = new XMLHttpRequest()
  xhr.open('GET', URL)
  xhr.send()
  xhr.onload = () => {
    if (xhr.status === 200) {
      todo = JSON.parse(xhr.response)
      return
    }
    console.error('ERROR!')
  }
}

get('https://jsonplaceholder.typicode.com/posts/1')
console.log('1.', todo)
setTimeout(() => {
  console.log('2.', todo)
}, 1000)

/* 출력 
1. undefined
2. {데이터}
*/
```

- 실행 순서를 보면 1. get함수가 실행이 된다. (차근 차근 진행되고 onload를 만나면 비동기함수이므로 태스크 큐에 넣어둔다. 그리고 그 뒤는 없으니 끝)

2. get함수가 끝났으니 콘솔을 실행한다. 이때 todo는 아무것도 없으니 undefined 출력
3. setTimeout비동기 함수를 만났으니 태스크 큐에 넣어준다. 그러고 끝
4. 코드는 다 끝났고 콜스택도 비워져 있으니 태스크 큐에 넣어둔 함수들을 차근차근 실행하며 onload를 먼저 실행하여 todo에 데이터를 할당하게 되고 setTimeout함수를 실행될때에는 todo에 데이터가 들어가 있게 된다.

<aside>
💡 이렇듯 비동기 함수는 비동기 처리 결과를 반환할수도 없고, 상위 스코프의 변수에도 할당할 수가 없다. 이를 해결하기 위해 주로 콜백함수를 전달하여 사용하게 된다.

</aside>

```jsx
let todo
const get = (URL, setTodo) => {
  const xhr = new XMLHttpRequest()
  xhr.open('GET', URL)
  xhr.send()
  xhr.onload = () => {
    if (xhr.status === 200) {
      setTodo(JSON.parse(xhr.response))
      return
    }
    console.error('ERROR!')
  }
}

const setTodo = (result) => {
  todo = result
  console.log('in', todo)
}

get('https://jsonplaceholder.typicode.com/posts/1', setTodo)

console.log('out', todo)
/* 출력 
	out undefined
	in {데이터}
*/
```

> 근데 콜백 함수 하나를 쓰는거 가지고는 어떤 이점이 있는지 아직 모르겠다. 별 다른 점을 못느낌... 여러개 콜백함수를 겹쳐서 저 response값을 사용하는 함수들로 연결연결해서 사용해야 좀 의미가 있다고 생각한다.

**45.1.2 에러 처리의 한계**

```jsx
try {
  setTimeout(() => {
    throw new Error('Error!')
  }, 1000)
} catch (e) {
  console.log('에러', e)
}
```

- catch문에서 에러를 잡지 못한다
- 왜냐하면 setTimeout함수의 콜백함수(에러함수)가 실행될때 이 콜백함수를 호출한 함수가 더이상 setTimeout함수가 아니다. (setTimeout함수는 이미 콜 스택에서 제거된 상태이다) 따라서 콜백함수가 실행이되고 에러가 발생한다고 한들 그 에러를 catch문에서 잡지 못한다 (try문 안에서 발생한 에러라고 인지를 못한다)

### 45.2 프로미스의 생성

- 프로미스는 비동기 처리 상태과 처리 결과를 관리하는 객체이다.

| 프로미스의 상태 정보 | 의미                                  | 상태 변경 조건                   |
| -------------------- | ------------------------------------- | -------------------------------- |
| pending              | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled            | 비동기 처리가 수행된 상태(성공)       | resolve함수 호출                 |
| rejected             | 비동기 처리가 수행된 상태(실패)       | reject함수 호출                  |

- 비동기 처리 성공 : resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경
- 비동기 처리 실패 : reject 함수를 호출해 프로미스를 rejected 상태로 변경
- 따라서 프로미스의 상태를 어떤 함수를 호출하느냐에 따라 결정된다.

**settled 상태**

- fulfilled, rejected상태 모두 settled상태라고 한다.
  즉, 비동기 처리가 수행된 상태를 나타낸다.
- 한번 settled 상태가 되면 다른 상태로 변할 수 없다.

### 45.3 프로미스의 후속 처리 메서드

- then, catch, finally
- 후속 처리 메서드의 콜백함수에 프로미스의 처리결과가 인수로 전달된다.
- 모든 후속 처리 메서드는 프로미스를 반환하고 비동기로 동작한다.

**then**

- 두개의 콜백 함수를 인수로 전달 받는다.
- 첫번째 콜백함수는 resolve상태일때, 두번째 콜백함수는 reject상태일때 실행됨

```jsx
new Promise((resolve, reject) => resolve('fulfilled')).then(
  (pass) => console.log('pass', pass),
  (error) => console.log('error', error)
)

new Promise((resolve, reject) => reject(new Error('rejected'))).then(
  (pass) => console.log('pass', pass),
  (error) => console.log('error', error)
)
/* 출력 
pass fulfilled
error Error: rejected
    at test.js:23
*/
```

**catch**

- 한개의 콜백함수를 인수로 전달 받는다.
- 이 콜백함수는 프로미스의 상태가 rejected일때만 호출 된다.
- then과 인수를 받는 갯수, 실행 조건만 다를뿐 굉장히 유사하다.

**finally**

- 한개의 콜백함수를 인수로 전달 받는다.
- 성공/실패와 상관없이 무조건 콜백함수를 호출한다.

**적용코드**

```jsx
const promiseGet = (URL) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    xhr.open('GET', URL)
    xhr.send()
    xhr.onload = () => {
      if (xhr.status === 200) {
        resolve(JSON.parse(xhr.response))
      } else {
        reject(new Error(xhr.status))
      }
    }
  })
}

promiseGet('https://jsonplaceholder.typicode.com/posts/1')
  .then((res) => console.log(res))
  .catch((err) => console.log(err))
  .finally(() => console.log('bye~'))

// promise 상태는 fulfilled이다.
/* 출력
	{데이터}
	bye~
*/
```

### 45.4 프로미스의 에러 처리

- 앞서 코드를 봤듯이 then의 두번째 인수로 받는 콜백함수를 이용해서 에러를 처리 할 수 있고, catch를 사용해서도 에러를 처리 할 수 있다.
- 사실 catch 메서드는 내부적으로 `then(undefined, onRejected)`을 호출하여 실행된다. 따라서 catch메서드 대신 then을 사용해도 괜찮아 보인다.
- 그럼에도 catch메서드를 사용하는 이유는 크게 2가지가 있다.
  1. then 메서드로 에러를 잡을 경우 첫번째 콜백함수에서 발생하는 에러를 잡지 못한다.
     반면 catch 메서드는 then 메서드 호출 이후에 작성한다면 **then메서드 내부에서 발생하는 에러까지 모두 잡을 수 있다.**
  2. then메서드에 2개의 콜백함수를 작성하는 것보다 **가독성**이 훨씬 좋다.

### 45.5 프로미스 체이닝

- 후속 처리 메서드는 언제나 프로미스를 반환하기 때문에 연속적으로 호출이 가능하다.

### 45.7 마이크로태스크 큐

```jsx
setTimeout(() => console.log(1), 0)

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3))
```

- 위 코드는 모두 비동기로 동작하기 때문에 1-2-3순서로 실행이 될 것 같지만 프로미스의 후속 처리 메서드의 콜백 함수는 일반적으로 비동기 함수가 담기는 태스크 큐로 가는게 아니라 마이크로태스크 큐에 담긴다.
- 태스크 큐, 마이크로태스크 큐 모두 콜백함수 또는 이벤트 핸들러를 임시 저장하다는 점에서 같은 역할을 하지만 마이크로태스크 큐가 태스크 큐보다 우선순위가 높기 때문에 위 코드의 결과는 2-3-1이 된다.

# 정리

이전에 과제를 하면서 비동기 함수를 다른 파일에 작성하고 그 함수를 import해서 사용할때 마다 자꾸 undefined가 나오는 문제가 있어서 한참 찾아보고 억지로 억지로 해결을 했던 기억이 있다. 이번 promise장을 보면서 왜 이런 문제가 있었는지 문제의 원인을 명확히 파악하게 되었다. 하지만 아직 promise객체에서 데이터를 뽑아오는 부분은 확실히 파악이 안되서 추가적인 공부가 필요하다.
